[general]
import = ["~/.config/alacritty/themes/catppuccin-frappe.toml"] # frappe, latte, macchiato, mocha
live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.9
blur = true
# padding.x = 10
# padding.y = 10
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 25
y = 20

[selection]
save_to_clipboard = true
# semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
hide_when_typing = true



[font]
size = 14.0

[font.normal]
family = "Roboto Mono"
style = "Regular"

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"
